const info = [{
    id: 1,
    category: 'family',
    engword: 'Mom',
    spanword: 'madre',
    img: "./image/momdance.jpeg",
    },
    {
    id: 2,
    category: 'family',
    engword: 'sister',
    spanword: 'hermana',
    img: "./image/brosis.jpeg",
    },
    {
    id: 3,
    category: 'family',
    engword: 'Dad',
    spanword: 'padre',
    img: "./image/dadsing.jpeg",
    },
    {
    id: 4,
    category: 'family',
    engword: 'brother',
    spanword: 'hermano',
    img: "./image/brosis.jpeg",
    },
    {
    id: 5,
    category: 'family',
    engword: 'Aunt',
    spanword: 'Tia',
    img: "./image/aunt.jpeg",
    },
    {
    id: 6,
    category: 'color',
    engword: 'red',
    spanword: 'rojo',
    img: "./image/redapple.jpeg",
    },
    {
    id: 7,
    category: 'color',
    engword: 'blue',
    spanword: 'azul',
    img: "./image/bluenose.jpeg",

    },
{
    id: 8,
    category: 'color',
    engword: 'green',
    spanword: 'verde',
    img: "./image/greenluck.jpeg",
    },
    {
    id: 9,
    category: 'color',
    engword: 'yellow',
    spanword: 'amarillo',
    img: "./image/yellow.jpeg",
    },
    {
    id: 10,
    category: 'color',
    engword: 'white',
    spanword: 'blanco',
    img: "./image/whitemilk.jpeg",
    },
    {
    id: 11,
    category: 'commonp',
    engword: 'hi',
    spanword: 'hola',
    img: "./image/whitemilk.jpeg",
    },
    {
    id: 12,
    category: 'commonp',
    engword: 'bye',
    spanword: 'adios',
    img: "./image/cry.jpeg",
    },
    {
    id: 13,
    category: 'commonp',
    engword: 'thanks',
    spanword: 'gracias',
    img: "./image/lunchdinner.jpeg",
    },
    {
    id: 14,
    category: 'commonp',
    engword: "i don't know",
    spanword: 'no se',
    img: "./image/bluenose.jpeg",
    },
{
id: 15,
category: 'commonp',
engword: 'good luck',
spanword: 'buena suerte',
img: "./image/greenluck.jpeg",
},
{
id: 16,
category: 'verb',
engword: 'eat',
spanword: 'comer',
img: "./image/yellow.jpeg",
},
{
id: 17,
category: 'verb',
engword: 'drink',
spanword: 'beber',
img: "./image/lunchdinner.jpeg",
},
{
id: 18,
category: 'verb',
engword: 'cry',
spanword: 'llorar',
img: "./image/cry.jpeg",
},
{
id: 19,
category: 'verb',
engword: 'sing',
spanword: 'cantar',
img: "./image/dadsing.jpeg",
},
{
id: 20,
category: 'verb',
engword: 'dance',
spanword: 'baila',
img: "./image/momdance.jpeg",
},
{
id: 21,
category: 'foodd',
engword: 'milk',
spanword: 'leche',
img: "./image/whitemilk.jpeg",
},
{
id: 22,
category: 'foodd',
engword: 'apple',
spanword: 'manzana',
img: "./image/redapple.jpeg",
},
{
id: 23,
category: 'foodd',
engword: 'breakfast',
spanword: 'desayuno',
img: "./image/breakfast.jpeg",
},
{
id: 24,
category: 'foodd',
engword: 'lunch',
spanword: 'almuerzo',
img: "./image/lunchdinner.jpeg",
},
{
id: 25,
category: 'foodd',
engword: 'dinner',
spanword: 'cena',
img: "./image/lunchdinner.jpeg",
},
{
id: 26,
category: 'ditem',
engword: 'car',
spanword: 'coche',
img: "./image/carcasa.jpeg",
},
{
id: 27,
category: 'ditem',
engword: 'house',
spanword: 'casa',
img: "./image/carcasa.jpeg",
},
{
id: 28,
category: 'ditem',
engword: 'bag',
spanword: 'bolsa',
img: "./image/bag.jpeg",
},
{
id: 29,
category: 'ditem',
engword: 'book',
spanword: 'libro',
img: "./image/book.jpeg",
},
{
id: 30,
category: 'ditem',
engword: 'chair',
spanword: 'silla',
img: "./image/chair.jpeg",
}
];

export default info;